### ISSUE TITLE
Unable to get this action to work. nothing seems to happen

### ISSUE THREAD

**Issue by qvistgaard** [helm/chart-testing-action#29]
So basically this is what i'm trying todo:

```(yaml)
 - name: Run chart-testing (lint)
    id: lint
    uses: helm/chart-testing-action
    with:
      command: lint
      config: ./ct.yaml
```
Nothing seems to work. To be upfront, i'm sorry if what i'm going to state is hurting someone's feelings, this project looks awesome, but:

 I started to dig a little into it, but i can't seem to grasp what you are trying achieve. I don't get the path you are taking:
- call node `main.js`
  - call `main.sh`
    - call `ct.sh`
      - start a docker container and manage it's runtime

So far from what i can see is that any possibility of using document configuration via environment variables are gone. and input variables doesn't seem to do anything at all. I'm no javascript guru, but correct me if I'm wrong: the inputs are never passed onto to main.sh as I see it? Also running the docker container detached makes it impossible to debug, what output actually comes from it.

- Why are you using a javascript file to spawn a new process?
- Why are we going through parsing commandline arguments twice?
- Why are you managing the docker container runtime yourself?
- Why not make this action a docker action?

If you wan't some input, i would love to make a pull request fixing all of the issues stated, however I don't want to put in the time if it will not be appreciated?

**Comment by scottrigby** [comment]
Hi thanks for your feedback. I'm hearing a few questions:

1. How can I get this to work?
1. Why did you choose the pattern you did for this action?

Assuming that's right:

1. How:
    - Action inputs are specified in [action.yml](https://github.com/helm/chart-testing-action/blob/master/action.yml), and documented in the [README](https://github.com/helm/chart-testing-action#inputs).
    - There are a number of public helm repos using `@helm/chart-testing-action`, following this example. This is just to say it does work
    - Chart testing configuration for this action should be done by specifying a config file. You can see a working example in the `helm/charts-repo-actions-demo` [Lint and Test Charts workflow]( https://github.com/helm/charts-repo-actions-demo/blob/master/.github/workflows/lint-test.yaml).
    - In your example above, you'll also want to specify the action ref (see [using versioned actions](https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#example-using-versioned-actions)). Again see how this is done in the `helm/charts-repo-actions-demo` workflows

2. Why:
    - We chose the [JavaScript option](https://help.github.com/en/actions/building-actions/creating-a-javascript-action) option for `@helm/chart-testing-action` because – while some `ct` commands can be run independently (like `lint`) – some `ct` commands (`install`, `lint-and-install`) require a working Kubernetes cluster
    - Note: we encourage using [@helm/kind-action](https://github.com/helm/kind-action), as it was built for this purpose)
    - Because this action must interact with a cluster, it must be able to interact with the functional k8s cluster through a KUBECONFIG. When we built this action there wasn't a clear path on how to do that using the [Dockerfile option](https://help.github.com/en/actions/building-actions/dockerfile-support-for-github-actions).
    - Maybe this action could be refactored to use the Dockerfile option.

**Comment by ssoerensen** [comment]
Hi @scottrigby 

Thanks for getting back to me regarding my rant :-)

I will give it another try to see if I can get it to work.

As to your question. You will be able to get all the features you need. The entire workspace is mounted directly inside the docker container. therefore the kubeconf and ct.conf will be available. 
Further more you will be able to get rid of the complexity of the current call path going through js and shell scripts (including all the docker container management that is being done). it should possible to get all logs as well



If you like i would be more then happy to make a pull request to show how it can be implemented.

**Comment by unguiculus** [comment]
You can either use JavaScript or a Docker. Unfortunately, there's no other choice. As @scottrigby pointed out, the only way for us is JavaScript because we need to create Kubernetes clusters for testing using kind. Docker actions have a number of limitations which don't allow that.

We use as little JavaScript as possible just calling a shell script which can be indepenently run and tested. Most actions out there are based on GitHub's action starters which require an NPM build. IMHO this is a pain to develop and test because it requires running an NPM build and committing build artifacts.

The whole logic is in a shell script which IMHO should be easier to understand than a lot of JavaScript code that needs to be compiled and that calls out to the shell instead.

The script `ct.sh` is to be seen as an independent shell script that can be run and tested in isolation and is just called by the GitHub action. As such, it has a set of parameters that the script has to parse.

The script `main.sh` is only there to parse action inputs so they can be passed to `ct.sh`. One could certainly merge the scripts but then `ct.sh` would incorporate GH action logic which I rather have decoupled and the script would be harder to test in isolation.

The script `main.js` is the entrypoint and pretty much the minimal amount of JavaScript need to call `main.sh`. It can be used as is. It does not use any dependencies and, thus, does not require an NPM build.

**Comment by unguiculus** [comment]
Closing this now. Feel free to open a new issue if you still have questions.
